#!/usr/bin/env python3
"""Generate robots.txt so every named crawler group repeats every Disallow.

This exists because of a real leak. robots.txt groups are NOT additive. From
Google's own spec:

    "Google's crawlers determine the correct group of rules by finding in the
     robots.txt file the group with the most specific user agent that matches
     the crawler's user agent. ... User agent specific groups and global
     groups (*) are not combined."

The file used to put the Disallow lines under `User-agent: *` and then declare
fifteen named AI crawlers with their own `Allow: /` groups. Every one of those
named crawlers therefore ignored the * group ENTIRELY — including
`Disallow: /talents/names.json`, the file holding every talent's real name.
The crawlers we most explicitly invited were the only ones not excluded from it.

Hand-editing a file with sixteen groups that must stay identical is how that
happened. So it is generated now: one list of rules, repeated into every group.

    python3 tools/build-robots.py
"""
import io, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'robots.txt')

PRIVATE = [
    ('Talent privacy. names.json is the only published file holding a talent\'s\n'
     '# real name, and it exists so a visitor\'s browser can paint names onto the\n'
     '# roster. No crawler may read it. _data/ holds the source roster.\n'
     '# Talent contact details exist nowhere on this site at all.',
     ['/talents/names.json', '/_data/']),
    ('Internal client review and photo-selection pages.',
     ['/contact-sheet.html', '/cs-couple.html', '/cs-rukmini.html',
      '/cs-wedding.html', '/ruk-choose.html', '/review.html']),
    ('Unfinished previews and scratch pages — not for indexing.',
     ['/_hero-preview.html', '/hero-motion-preview.html', '/work-preview.html',
      '/_fonts-preview.html', '/edit.html', '/studio.html', '/labs.html',
      '/yks-productions-onepage.html']),
]

# Answer engines we want citing us. Each needs its own full copy of the rules.
# Names taken from each vendor's own crawler documentation, not from
# SEO blog posts. Claude-Web and anthropic-ai were dropped: Anthropic's
# support article documents exactly three agents and neither is among them.
# Claude-User and Claude-SearchBot are the two that actually fetch a page
# to answer a question, which is the surface we care about.
AI = ['GPTBot', 'OAI-SearchBot', 'ChatGPT-User',
      'ClaudeBot', 'Claude-User', 'Claude-SearchBot',
      'PerplexityBot', 'Perplexity-User', 'Google-Extended',
      'Applebot', 'Applebot-Extended', 'Bingbot', 'CCBot',
      'Meta-ExternalAgent', 'Meta-WebIndexer', 'Meta-ExternalFetcher',
      'Amazonbot', 'DuckAssistBot', 'cohere-ai', 'YouBot']


def rules():
    out = []
    for note, paths in PRIVATE:
        out.append('  # ' + note.replace('\n# ', '\n  # '))
        out += [f'  Disallow: {p}' for p in paths]
    return '\n'.join(out).replace('  #', '#').replace('  Disallow', 'Disallow')


BLOCK = rules()
parts = ['''# robots.txt — GENERATED by tools/build-robots.py. Do not hand-edit.
#
# Every group below repeats the same Disallow list, deliberately. robots.txt
# groups are not combined: a crawler with its own named group ignores the
# global "*" group completely. A rule that appears only under "*" does not
# apply to any named crawler.
''']

parts.append('User-agent: *\n' + BLOCK + '\nAllow: /\n')
parts.append('''# ─────────────────────────────────────────────────────────────
# AI assistants and answer engines — explicitly welcome to the
# public site, and explicitly excluded from the private files.
# See /llms.txt for a clean summary of the business.
# ─────────────────────────────────────────────────────────────
''')
for bot in AI:
    parts.append(f'User-agent: {bot}\n' + BLOCK + '\nAllow: /\n')

parts.append('Sitemap: https://yksproductions.com/sitemap.xml\n')
io.open(OUT, 'w', encoding='utf-8').write('\n'.join(parts))

# ── the check that would have caught the leak ──
txt = io.open(OUT, encoding='utf-8').read()
groups, cur = {}, None
for line in txt.splitlines():
    line = line.strip()
    if line.lower().startswith('user-agent:'):
        cur = line.split(':', 1)[1].strip()
        groups[cur] = set()
    elif line.lower().startswith('disallow:') and cur:
        groups[cur].add(line.split(':', 1)[1].strip())

must = {p for _, ps in PRIVATE for p in ps}
bad = [g for g, d in groups.items() if not must.issubset(d)]
print(f'groups written : {len(groups)}')
print(f'rules per group: {len(must)}')
if bad:
    print('BUILD ABORTED — these groups do not exclude the private paths:')
    for g in bad:
        print('  ✗', g, sorted(must - groups[g]))
    sys.exit(1)
print('every group excludes every private path ✓')
